[package]
name = "contract"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.20"
syn = { features = ["parsing", "full", "visit", "extra-traits"] }
proc-macro2 = "1.0.40"
fvm-ir = { path = "../ir" }
fvm_codegen = { path = "../codegen" }
